export const demoDeepDives: Record<string, string> = {
  "The POSH Act turns a decade old - enforcement still lags in practice": `The law asks workplaces with at least ten employees to create an Internal Committee that can receive and examine sexual-harassment complaints. A district-level Local Committee is meant to cover smaller workplaces and cases involving an employer. Those routes matter because they give a worker an option beyond reporting directly to the same manager or organisation involved.

The gap between a rule and a remedy often appears in implementation. A committee may exist only on paper, members may not be trained, workers may not know how to reach it, or the required outside member may not be meaningfully independent. Smaller organisations and informal arrangements can be especially difficult to navigate. Counting committees therefore does not tell us whether a complaint was handled safely, promptly, and without retaliation.

For workers, the practical questions are simple but important: who sits on the committee, how can it be contacted privately, what timeline applies, and what support exists during an inquiry? For employers, compliance is not a one-time document. It includes prevention training, a credible process, confidentiality, annual reporting, and protection against retaliation.`,
  "Nirbhaya Fund utilisation remains a recurring flashpoint in Parliament": `The Nirbhaya Fund was created to support projects intended to improve women's safety. Different ministries and state governments can propose projects, which then move through appraisal, approval, release, and implementation. That chain is why several different numbers may appear in public discussion: money allocated, money released, and money actually used are not the same measure.

Slow spending can reflect delayed procurement, incomplete state proposals, coordination problems, or projects that take years to build. But a high utilisation figure is not proof that women are safer either. A camera network, helpline, forensic laboratory, or transport programme still has to work reliably, reach the people it was designed for, and be maintained after launch.

The useful public-interest question is therefore not only how much was spent. It is what was delivered, where it operates, whether women can access it, and what outcome changed. Parliamentary replies, audit findings, and scheme dashboards are most meaningful when those stages are read together rather than as one headline percentage.`,
  "Marital rape exception remains under judicial review": `The legal dispute centres on an exception in India's rape law for sexual acts by a husband with his adult wife. Petitioners challenging the exception argue that marriage cannot remove a person's right to consent, bodily autonomy, and equal protection. Those defending the existing framework have raised questions about criminal law, evidence, and the relationship between courts and Parliament.

The issue is separate from saying that abuse within marriage has no legal consequences. Other criminal and civil remedies may apply to cruelty, assault, domestic violence, or related conduct. The narrower question before the courts is whether non-consensual sex within marriage should be treated under the same rape provision and, if so, how the law should be framed and applied.

Because this is an active legal question, careful reporting should distinguish an argument made in court from a final binding decision. It should also avoid presenting a survivor's marital status as evidence of consent. Titli keeps this card contested and links to the original reporting so readers can see the legal stage and competing submissions for themselves.`,
  "Menstrual leave policy remains patchy across Indian workplaces": `Menstrual leave is not one single policy. Some models offer a fixed number of paid days, some allow flexible or remote work, and others place menstrual symptoms within ordinary sick leave. Access can also depend on whether a person works for a state government, a private employer, or in an informal job. That produces a patchwork rather than a common entitlement.

Supporters say a specific policy acknowledges pain that is routinely minimised and lets people rest without hiding the reason. Critics worry that a separate category could reinforce stereotypes, invite intrusive proof, or give employers another reason to discriminate in hiring and promotion. Both concerns are about workplace power, not simply the number of leave days.

A well-designed policy has to answer practical questions: Is leave paid? Is medical evidence required? Who can see the request? Are contract and gig workers included? Can someone choose flexibility instead of disclosing a cycle? The strongest test is whether workers gain real choice without being penalised for using it.`,
  "Maternity Benefit Act's 26-week leave rarely reaches informal workers": `The 26-week entitlement is one of the most visible parts of India's maternity law, but its reach depends on the kind and size of establishment and on a worker meeting the law's eligibility conditions. That matters because many women earn through domestic work, agriculture, home-based production, casual labour, or other informal arrangements where an employer-funded paid-leave promise is difficult to claim.

Even within formal employment, a legal entitlement does not automatically remove barriers. Workers may be unclear about eligibility, employers may avoid compliance, and the cost being placed largely on employers can create discriminatory hiring incentives. Childcare and return-to-work support also shape whether a woman can actually remain in employment after leave ends.

For informal workers, maternity protection is more often discussed through public social-security and cash-support schemes, but coverage and adequacy vary. The broader policy question is who carries the cost of care. A right designed around a conventional employer-employee relationship will leave a large gap unless social protection also reaches workers outside that model.`,
  "Women's political reservation law awaits delimitation to take effect": `The constitutional amendment reserves one-third of seats in the Lok Sabha and state legislative assemblies for women, including within seats reserved for Scheduled Castes and Scheduled Tribes. The change is significant, but the law links its operation to a future census and the delimitation exercise that follows. It does not immediately change the composition of the current houses.

Delimitation redraws constituencies and determines how seats are distributed. Because implementation is tied to that process, the timetable depends on steps beyond the passage of the amendment itself. The reserved constituencies are also intended to rotate, so the eventual rules will affect how candidates, parties, and voters experience the system over successive elections.

India already has long experience with reservation for women in panchayats and municipalities, where representation has increased substantially even as debates continue about authority, party support, and proxy control. For the national law, the key things to watch are the census, delimitation legislation and rules, the first election covered, and how parties prepare women to contest winnable seats.`,
  "Two-finger test banned, but reporting shows the practice persists": `The so-called two-finger test has no scientific basis for deciding whether sexual assault occurred. It examines vaginal laxity or makes observations about sexual history, neither of which can establish consent. Courts and health guidance have rejected the practice because it is invasive, irrelevant to the central question, and harmful to a survivor's dignity.

Ending the test requires more than a judicial direction. Medical forms must be updated, doctors and police need training, hospitals need appropriate forensic kits, and supervisors must identify old practices that continue by habit. Survivors also need examinations focused on treatment, documentation of relevant injuries, informed consent, and preservation of evidence without moral judgement.

Responsible reporting should not repeat intimate findings that have no evidentiary value. It should ask whether current medical protocols were followed and whether the survivor received care and support. A person's past sexual activity never proves consent to the incident being investigated.`,
  "Anganwadi and ASHA workers, mostly women, still classified as 'volunteers'": `ASHA and Anganwadi workers connect public systems to families at the neighbourhood level. Their work can include maternal and child health support, immunisation follow-up, nutrition services, surveys, record-keeping, home visits, and responding during public-health emergencies. The system relies on their local knowledge and trust, even though their employment classification does not resemble a standard salaried public post.

Payments are commonly structured through honorariums and task-based incentives, with amounts and additions varying across schemes and states. Workers and unions argue that this can mean unpredictable income, expanding duties, and limited access to protections associated with formal employment. Governments have periodically increased payments or benefits without resolving the larger demand for worker status.

The classification matters because it shapes minimum wages, social security, pensions, leave, insurance, and bargaining power. When reading a new announcement, the useful questions are whether it changes the base payment or only an incentive, whether every worker is covered, when funds will reach accounts, and whether employment rights change alongside the amount.`,
};

export function getDemoDeepDive(headline: string): string | undefined {
  const normalized = headline.replace(/[\u2013\u2014]/g, "-");
  return demoDeepDives[normalized];
}
